which_agent: 201
follow_trajectories: False

data_collection:
    use_threading: False
    num_rollouts_train: 60
    num_rollouts_val: 20

dyn_model:
    num_fc_layers: 1
    depth_fc_layers: 500
    batchsize: 512
    lr: 0.001
    nEpoch: 50
    fraction_use_new: 0.8

controller:
    horizon: 5
    num_control_samples: 15000
    N_factor: 1
    maxiter: 400
    num_MCscore: 10
    forward_particles: 1
    distributed: True

aggregation:
    num_aggregation_iters: 5000
    num_trajectories_for_aggregation: 2
    rollouts_forTraining: 2

noise:
    make_aggregated_dataset_noisy: True
    make_training_dataset_noisy: True
    noise_actions_during_MPC_rollouts: False

steps:
    dt_steps: 1
    steps_per_episode: 200
    steps_per_rollout_train: 200
    steps_per_rollout_val: 200

saving:
    min_rew_for_saving: 0

generic:
    visualize_True: True
    visualize_False: False
