which_agent: 103
follow_trajectories: False

data_collection:
    use_threading: False
    num_rollouts_train: 600
    num_rollouts_val: 200

dyn_model:
    num_fc_layers: 1
    depth_fc_layers: 500
    batchsize: 512
    lr: 0.001
    nEpoch: 2000
    fraction_use_new: 0.5

controller:
    horizon: 5
    num_control_samples: 15000
    N_factor: 500
    maxiter: 5
    num_MCscore: 10
    forward_particles: 1
    distributed: False

aggregation:
    num_aggregation_iters: 10000
    num_trajectories_for_aggregation: 2
    rollouts_forTraining: 2

noise:
    make_aggregated_dataset_noisy: True
    make_training_dataset_noisy: True
    noise_actions_during_MPC_rollouts: False

steps:
    dt_steps: 1
    steps_per_episode: 100
    steps_per_rollout_train: 100
    steps_per_rollout_val: 100

saving:
    min_rew_for_saving: 0

generic:
    visualize_True: True
    visualize_False: False
